name: Backend CI

on: 
  push:
    paths: 
    - 'backend/**'
    pull-request:
      paths: 
    - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
        - run: 'cd backend && go build .'
